### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by jlgit** [srchea/PHP-Push-WebSocket#10]
Hello;

First I'll like to thank you for this piece of code, I being looking for something like this for a good time already and just when I decided to create it myself I found yours... Thanks.

I was able to place it all in the same manner you have set in your test and after some debugging I was able to make it all work, the only problem is that I just keep getting the following answer when running from the client side:

WebSocket connection to 'ws://127.0.0.1:5001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

As you can see I'm running it on the same address/port you have in your test but there is no way to get it to work, I'm connecting from a computer in the same network of the server and the port 5001 is open on my server and waiting for connections, if you can please let me know what can I do to have it all working.

Thanks in advance.

**Comment by srchea** [comment]
Hey @jlgit,

The address 127.0.0.1 is the localhost, if your client is on another computer in the same network, you have to connect to an IP address like: 192.168.xxx.yyy. If there is no firewall or extra security on the network, that should work as expected.
