### ISSUE TITLE
telnet

### ISSUE THREAD

**Issue by zukasmichael** [srchea/PHP-Push-WebSocket#6]
try to telnet to 127.0.0.1:5001 and after connecting just close the connection. Server goes into infinite cycle to try a handshake or something. Not sure what is that - but nothing good

**Comment by coolcheat** [comment]
I've had that happen to me too but was unable to replicate the problem until I saw your post.

The fix is pretty easy, in Server.class.php go to line 235.
After that line add:
else
$this->disconnect($client);

**Comment by srchea** [comment]
Thanks both of you!
